name: ytodos
description: "A new Flutter project."
publish_to: none

version: 0.0.1+3

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  navigation:
    path: navigation
  core:
    path: core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0